#lang sicp
(#%require "interface.rkt")
(#%provide (all-defined))

(define (install-integer-package)
  (define (tag x)
    (attach-tag 'integer x))    
  (put 'add '(integer integer)
       (lambda (x y) (tag (+ x y))))
  (put 'sub '(integer integer)
       (lambda (x y) (tag (- x y))))
  (put 'mul '(integer integer)
       (lambda (x y) (tag (* x y))))
  (put 'div '(integer integer)
       (lambda (x y) (tag (round (/ x y)))))
  (put 'equ? '(integer integer)
       (lambda (x y) (= x y)))
  (put '=zero? '(integer)
       (lambda (x) (= x 0)))
  (put 'sine '(integer)
       (lambda (x) (sin x)))
  (put 'cosine '(integer)
       (lambda (x) (cos x)))
  (put 'make 'integer
       (lambda (x) (tag (round x))))
  'done)