#lang racket

(define (make-interval a b)
  (cons a b))

(define (lower-bound itvl)
  (car itvl))

(define (upper-bound itvl)
  (cdr itvl))

(define (add-interval x y)
  (make-interval (+ (lower-bound x) (lower-bound y))
                 (+ (upper-bound x) (upper-bound y))))

(define (sub-interval x y)
  (make-interval (- (lower-bound x) (lower-bound y))
                 (- (upper-bound x) (upper-bound y))))

(define (mul-interval x y)
  (let ((p1 (* (lower-bound x) (lower-bound y)))
        (p2 (* (lower-bound x) (upper-bound y)))
        (p3 (* (upper-bound x) (lower-bound y)))
        (p4 (* (upper-bound x) (upper-bound y))))
    (make-interval (min p1 p2 p3 p4)
                   (max p1 p2 p3 p4))))

(define (div-interval x y)
  (if (or (= (upper-bound y) 0)
          (= (lower-bound y) 0))
      (display "error")
      (mul-interval x 
                    (make-interval (/ 1.0 (upper-bound y))
                                   (/ 1.0 (lower-bound y))))))

(define (make-center-width c w)
  (make-interval (- c w) (+ c w)))
(define (center i)
  (/ (+ (lower-bound i) (upper-bound i)) 2))
(define (width i)
  (/ (- (upper-bound i) (lower-bound i)) 2))

(define (revised-mul x y)
  (define (positive? i)
    (>= (lower-bound i) 0))
  (define (negative? i)
    (< (upper-bound i) 0))
  (define (case i)
    (cond ((positive? i) 1)
          ((negative? i) -1)
          (else 0)))
  (let ((case-x (case x))
        (case-y (case y))
        (xl (lower-bound x))
        (xu (upper-bound x))
        (yl (lower-bound y))
        (yu (upper-bound y)))
    (cond ((and (= case-x 1) (= case-y 1)) (make-interval (* xl yl) (* xu yu)))
          ((and (= case-x 1) (= case-y 0)) (make-interval (* xu yl) (* xu yu)))
          ((and (= case-x 1) (= case-y -1)) (make-interval (* xu yl) (* xl yu)))
          ((and (= case-x -1) (= case-y 1)) (make-interval (* xl yu) (* xu yl)))
          ((and (= case-x -1) (= case-y 0)) (make-interval (* xl yu) (* xl yl)))
          ((and (= case-x -1) (= case-y -1)) (make-interval (* xu yu) (* xl yl)))
          ((and (= case-x 0) (= case-y 1)) (make-interval (* xl yu) (* xu yu)))
          ((and (= case-x 0) (= case-y -1)) (make-interval (* yl xu) (* xl yl)))
          (else (make-interval (min (* xl yu) (* xu yl)) (max (* xl yl) (* xu yu)))))))


(define (print-interval i)
  (display "(")
  (display (lower-bound i))
  (display ",")
  (display (upper-bound i))
  (display ")")
  (newline))

;; test part:

(define (mul-verifier n)
  
  (define (interval-equal? x y)
    (and (= (lower-bound x) (lower-bound y)) 
         (= (upper-bound x) (upper-bound y))))
  
  (define (interval-generator n)
    (let ((lower (random (- n) (- n 1))))
      (let ((upper (random lower n)))
        (make-interval lower upper))))
  (if (= n 0)
      (display "All tests pass!")
      (begin (let ((x (interval-generator n))
                   (y (interval-generator n)))
               (let ((remul (revised-mul x y))
                     (ogmul (mul-interval x y)))
                 (if (interval-equal? remul ogmul)
                     (mul-verifier (- n 1))
                     (begin 
                       (display "Tests failed: ")
                       (newline)
                       (display "x: ")
                       (print-interval x)
                       (display "y: ")
                       (print-interval y)
                       (display "re-mul: ")
                       (print-interval remul)
                       (display "og-mul: ")
                       (print-interval ogmul))
                     ))
               ))))

(mul-verifier 100)